# This is a basic workflow to help you get started with Actions

name: SCA


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the add-license-1 branch
  #push:
    #branches: [ add-license-1 ]
  #pull_request:
    #branches: [ add-license-1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      --run: export GOPATH = $(go env GOPATH); echo $GOPATH
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: export SRCCLR_API_TOKEN=${{ secrets.SRCCLR_API_TOKEN }} && /usr/bin/curl -sSL https://download.sourceclear.com/ci.sh | /bin/sh -s -- scan
#      - uses: montudor/action-zip@v1.0.0
